name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Stop old Docker process
      run: docker container stop nick-rheaume/portfolio

    - name: Remove old docker image
      run: docker container rm nick-rheaume/portfolio

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t nick-rheaume/portfolio .
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    #- name: Run the Docker image
     # run: docker container run nick-rheaume/portfolio
