name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Stop old Docker process
      run: docker container stop portfolio || true

    - name: Remove old docker container
      run: docker container rm portfolio || true

    #- name: Remove old docker image
    #  run: docker image rm nick-rheaume/portfolio || true

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t nick-rheaume/portfolio .

    - name: Run the Docker image
      run: docker container run -d -p 20000:8080 --name portfolio nick-rheaume/portfolio
